version: "3.8"
services:
  api:
    build:
      context: study
    container_name: "api"
    links:
      - mongo
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - mongo
      - kafka
    links:
      - kafka
      - mongo
    networks:
      - default
      - kafka-docker_backend
  mongo:
    image: mongo
    restart: always
    volumes:
      - /data/db:/data/db --user 1000
    container_name: "mongo"
    ports:
      - "27017:27017"
    expose:
      - "27017"
    networks:
      - default
      - kafka-docker_backend
  angular:
    build:
      context: angular
    container_name: "angular"
    links:
      - api
    restart: always
    ports:
      - "4500:4500"
    expose:
      - "4500"
    depends_on:
      - api
  consumer:
    build:
      context: kafka-consumer
    deploy:
      replicas: 3
    depends_on:
      - kafka
      - api
    links:
      - kafka
    networks:
      - default
      - kafka-docker_backend
networks:
  kafka-docker_backend:
    external: true