FROM node:14.17.3 AS build
RUN mkdir -p /app
COPY . /app
WORKDIR /app
RUN npm install -g npm
RUN npm install --save
RUN npm run build

FROM nginx:1.17.1-alpine
COPY --from=build app/dist/testBoard /usr/share/nginx/html

# optional
COPY default.conf /etc/nginx/conf.d/default.conf

